name: Build Module

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
        pip install setuptools_rust
        python ./setup.py develop
        python -m pip install -r tests/requirements.txt
        python -m unittest  tests/compatibility.py
